### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by AseiSugiyama**
Update OS image, Python runtime, imported libraries, and deprecated method of scikit-learn.

### CODE REVIEW

**Comment by AseiSugiyama** [comment]
I've checked it manually. Please take a review 🙏 
image

**Comment by AseiSugiyama** [comment]
@KUrushi @karno Could you review this PR, please?

**Review by karno — APPROVED** [review]
I've reviewed changesets and also checked runs on Vertex Pipelines. They seem to be good.

**Comment by AseiSugiyama** [comment]
@karno Thank you for your review! Could you merge this PR? I don't have permission to merge this PR.

**Pull request merged**
